const actions = {
  CREATE_LOG: "CREATE_LOG",
  UPDATE_EMPLOYEES: "UPDATE_EMPLOYEES",
  UPDATE_LOGS: "UPDATE_LOGS",
  SET_CURRENT_USER: "SET_CURRENT_USER",
  CLEAR_CURRENT_USER: "CLEAR_CURRENT_USER",
};

export default actions;
